RastradorPreco/Models/Produto.cs
namespace RastradorPreco.Models
{
    public class Produto
    {
        public int ProdutoId { get; set; }

        public string Nome { get; set; }

        public string LinkProduto { get; set; }
    }
}

RastradorPreco/Controllers/InformacoesConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using RastradorPreco.Models;
using System.Data.SqlClient;

namespace RastreadorPrecos.Controllers
{
    public class InformacoesConsultaController : Controller
    {
        private readonly string _connectionString = "Server=DESKTOP-O1775Q7;Database=RastreadorDb;User Id=sa;Password=123456;Trusted_Connection=True;TrustServerCertificate=True;";
        private readonly SqlConnection _connection;

        public InformacoesConsultaController()
        {
            _connection = new SqlConnection(_connectionString);
        }

        [HttpGet]
        public IActionResult NovaInformacao(int produtoId)
        {
            InformacoesConsulta ic = new InformacoesConsulta
            {
                ProdutoId = produtoId
            };
            return View(ic);
        }

        [HttpPost]
        public async Task<IActionResult> NovaInformacao(InformacoesConsulta ic)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string insercaoQuery = "INSERT INTO InformacoesConsulta(produtoId, Valor, Dia, Mes, Ano) VALUES(@ProdutoId, @Valor, @Dia, @Mes, @Ano)";
                    SqlCommand comando = new SqlCommand(insercaoQuery, _connection);
                    comando.CommandType = CommandType.Text;

                    comando.Parameters.AddWithValue("@produtoId", ic.ProdutoId);
                    comando.Parameters.AddWithValue("@Valor", ic.Valor);
                    comando.Parameters.AddWithValue("@Dia", ic.Dia);
                    comando.Parameters.AddWithValue("@Mes", ic.Mes);
                    comando.Parameters.AddWithValue("@Ano", ic.Ano);

                    await _connection.OpenAsync();
                    await comando.ExecuteNonQueryAsync();
                    return RedirectToAction("DetalhesProduto", "Produtos", new { produtoId = ic.ProdutoId });
                }

                return View(ic);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }
        }
    }
}

RastradorPreco/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System;
using System.Data.SqlClient;
using System.Threading.Tasks;
using RastradorPreco.Models;
using System.Collections.Generic;

namespace RastradorPreco.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly string _connectionString = "Server=DESKTOP-O1775Q7;Database=RastreadorDb;User Id=sa;Password=123456;Trusted_Connection=True;TrustServerCertificate=True;";
        private readonly SqlConnection _connection;

        public ProdutosController()
        {
            _connection = new SqlConnection(_connectionString);
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                List<Produto> listaProdutos = new List<Produto>();
                string selecaoQuery = "SELECT * FROM produtos";

                SqlCommand comando = new SqlCommand(selecaoQuery, _connection);
                comando.CommandType = CommandType.Text;

                await _connection.OpenAsync();
                SqlDataReader leitorDados = await comando.ExecuteReaderAsync();

                while (await leitorDados.ReadAsync())
                {
                    Produto produto = new Produto();
                    produto.ProdutoId = Convert.ToInt32(leitorDados["ProdutoId"]);
                    produto.Nome = leitorDados["Nome"].ToString();
                    produto.LinkProduto = leitorDados["LinkProduto"].ToString();
                    listaProdutos.Add(produto);
                }

                return View(listaProdutos);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }


        }

        [HttpGet]
        public IActionResult NovoProduto()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NovoProduto(Produto produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string insercaoQuery = "INSERT INTO Produtos(Nome, LinkProduto) VALUES(@Nome, @LinkProduto)";
                    SqlCommand comando = new SqlCommand(insercaoQuery, _connection);
                    comando.CommandType = CommandType.Text;

                    comando.Parameters.AddWithValue("@Nome", produto.Nome);
                    comando.Parameters.AddWithValue("@LinkProduto", produto.LinkProduto);

                    await _connection.OpenAsync();
                    await comando.ExecuteNonQueryAsync();

                    return RedirectToAction(nameof(Index));
                }

                return View(produto);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }
        }

        [HttpGet]
        public async Task<IActionResult> AtualizarProduto(int produtoId)
        {
            try
            {
                string selecaoQuery = String.Format("SELECT * FROM Produtos WHERE ProdutoId = {0}", produtoId);
                SqlCommand comando = new SqlCommand(selecaoQuery, _connection);
                Produto produto = new Produto();

                await _connection.OpenAsync();
                SqlDataReader leitorDados = await comando.ExecuteReaderAsync();

                while (await leitorDados.ReadAsync())
                {
                    produto.ProdutoId = Convert.ToInt32(leitorDados["ProdutoId"]);
                    produto.Nome = leitorDados["Nome"].ToString();
                    produto.LinkProduto = leitorDados["LinkProduto"].ToString();
                }

                return View(produto);

            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AtualizarProduto(int produtoId, Produto produto)
        {
            try
            {
                if (produtoId != produto.ProdutoId)
                    return NotFound();

                if (ModelState.IsValid)
                {
                    string atualizacaoQuery = "UPDATE Produtos SET Nome = @Nome, LinkProduto = @LinkProduto WHERE ProdutoId = @ProdutoId";
                    SqlCommand comando = new SqlCommand(atualizacaoQuery, _connection);
                    comando.CommandType = CommandType.Text;

                    comando.Parameters.AddWithValue("@ProdutoId", produto.ProdutoId);
                    comando.Parameters.AddWithValue("@Nome", produto.Nome);
                    comando.Parameters.AddWithValue("@LinkProduto", produto.LinkProduto);

                    await _connection.OpenAsync();
                    await comando.ExecuteNonQueryAsync();

                    return RedirectToAction(nameof(Index));
                }

                return View(produto);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }
        }

        [HttpPost]
        public async Task<IActionResult> ExcluirProduto(int produtoId)
        {
            try
            {
                string exclusãoQuery = "DELETE FROM Produtos WHERE ProdutoId = @ProdutoId";
                SqlCommand comando = new SqlCommand(exclusãoQuery, _connection);
                comando.CommandType = CommandType.Text;

                comando.Parameters.AddWithValue("@ProdutoId", produtoId);

                await _connection.OpenAsync();
                await comando.ExecuteNonQueryAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }

        }

        public async Task<IActionResult> DetalhesProduto(int produtoId)
        {
            try
            {
                ViewData["ProdutoId"] = produtoId;
                List<InformacoesConsulta> listaIC = new List<InformacoesConsulta>();
                string selecaoQuery = String.Format("SELECT Valor, Dia, Mes, Ano FROM InformacoesConsulta WHERE ProdutoId = {0}", produtoId);
                SqlCommand comando = new SqlCommand(selecaoQuery, _connection);

                await _connection.OpenAsync();
                SqlDataReader leitorDados = await comando.ExecuteReaderAsync();

                while (await leitorDados.ReadAsync())
                {
                    InformacoesConsulta ic = new InformacoesConsulta();
                    ic.Valor = Convert.ToDouble(leitorDados["Valor"]);
                    ic.Dia = Convert.ToInt32(leitorDados["Dia"]);
                    ic.Mes = Convert.ToInt32(leitorDados["Mes"]);
                    ic.Ano = Convert.ToInt32(leitorDados["Ano"]);
                    listaIC.Add(ic);
                }

                return View(listaIC);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }
        }

        public async Task<JsonResult> DadosGrafico(int produtoId, int diaInicio, int diaFim, int mes, int ano)
        {
            try
            {
                List<InformacoesConsulta> listaIC = new List<InformacoesConsulta>();
                string selecaoQuery = String.Format("SELECT Valor, Dia, Mes, Ano " +
                    "FROM InformacoesConsulta " +
                    "WHERE (produtoId = {0} AND Ano = {1} AND Mes = {2} AND (Dia >= {3} AND Dia <= {4}))", produtoId, ano, mes, diaInicio, diaFim);
                SqlCommand comando = new SqlCommand(selecaoQuery, _connection);

                await _connection.OpenAsync();
                SqlDataReader leitorDados = await comando.ExecuteReaderAsync();

                while (await leitorDados.ReadAsync())
                {
                    InformacoesConsulta ic = new InformacoesConsulta();
                    ic.Valor = Convert.ToDouble(leitorDados["Valor"]);
                    ic.Dia = Convert.ToInt32(leitorDados["Dia"]);
                    ic.Mes = Convert.ToInt32(leitorDados["Mes"]);
                    ic.Ano = Convert.ToInt32(leitorDados["Ano"]);
                    listaIC.Add(ic);
                }

                return Json(listaIC);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            finally
            {
                await _connection.CloseAsync();
            }
        }
    }
}

RastradorPreco/Views/Produtos/AtualizarProduto.cshtml
@model RastradorPreco.Models.Produto

@{
    ViewData["Title"] = "Atualizar Produto " + Model.Nome;
}



<h4>Atualizar Produto @Model.Nome</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AtualizarProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="ProdutoId" type="hidden" />

            <div class="form-group">
                <label asp-for="Nome" class="control-label col-form-label-sm"></label>
                <input asp-for="Nome" class="form-control form-control-sm" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkProduto" class="control-label col-form-label-sm"></label>
                <input asp-for="LinkProduto" class="form-control form-control-sm" />
                <span asp-validation-for="LinkProduto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-outline-info btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>

RastradorPreco/Views/Produtos/DetalhesProduto.cshtml
@model IEnumerable<RastradorPreco.Models.InformacoesConsulta>

@{
    ViewData["Title"] = "Detalhes do Produto";
}

<input type="hidden" id="ProdutoId" value="@ViewData["ProdutoId"]" />


<div class="container">
    <div class="row alert alert-secondary">
        <div class="input-group">
            <div class="col-1 p-0">
                <select class="form-control form-control-sm" id="diaInicio">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                    <option value="31">31</option>
                </select>
            </div>

            <div>
                <div class="input-group-prepand">
                    <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </div>
            </div>

            <div class="col-1 p-0">
                <select class="form-control form-control-sm" id="diaFim">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                    <option value="13">13</option>
                    <option value="14">14</option>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                    <option value="21">21</option>
                    <option value="22">22</option>
                    <option value="23">23</option>
                    <option value="24">24</option>
                    <option value="25">25</option>
                    <option value="26">26</option>
                    <option value="27">27</option>
                    <option value="28">28</option>
                    <option value="29">29</option>
                    <option value="30">30</option>
                    <option value="31">31</option>
                </select>
            </div>

            <div class="col-4 p-0">
                <select id="mes" class="form-control form-control-sm">
                    <option value="1">Janeiro</option>
                    <option value="2">Fevereiro</option>
                    <option value="3">Março</option>
                    <option value="4">Abril</option>
                    <option value="5">Maio</option>
                    <option value="6">Junho</option>
                    <option value="7">Julho</option>
                    <option value="8">Agosto</option>
                    <option value="9">Setembro</option>
                    <option value="10">Outubro</option>
                    <option value="11">Novembro</option>
                    <option value="12">Dezembro</option>
                </select>
            </div>

            <div class="col-4 p-0">
                <button type="button" class="btn btn-outline-secondary btn-sm" id="btnFiltro">Filtar</button>
            </div>

        </div>
    </div>
</div>
<hr />

<canvas id="grafico"></canvas>



<p>
    <a asp-action="NovaInformacao" asp-controller="InformacoesConsulta" asp-route-produtoId="@ViewData["ProdutoId"]" class="btn btn-outline-success btn-sm">Nova Informação</a>
</p>
<table class="table table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th>
                Valor
            </th>
            <th>
                Data da consulta
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    R$ @item.Valor
                </td>
                <td>
                    @String.Format("{0}/{1}/{2}", item.Dia, item.Mes, item.Ano)
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        $(document).ready(function () {
            const produtoId = parseInt($("#ProdutoId").val());
            const diaInicio = 1;
            const diaFim = 31;
            const mes = new Date().getMonth() + 1;
            const ano = new Date().getFullYear();
            PegarDados(produtoId, diaInicio, diaFim, mes, ano);
        });

        $("#btnFiltro").on('click', function () {
            const produtoId = parseInt($("#ProdutoId").val());
            const diaInicio = parseInt($("#diaInicio").val());
            const diaFim = parseInt($("#diaFim").val());
            const mes = parseInt($("#mes").val());
            const ano = new Date().getFullYear();

            if (diaInicio > diaFim) {
                alert("Datas inválidas");
            }
            else {
                PegarDados(produtoId, diaInicio, diaFim, mes, ano);
            }
        });

        function PegarDados(produtoId, diaInicio, diaFim, mes, ano) {
            $.ajax({
                method: "GET",
                url: "/Produtos/DadosGrafico",
                data: { produtoId: produtoId, diaInicio: diaInicio, diaFim: diaFim, mes: mes, ano: ano },
                success: function (dados) {
                    new Chart(document.getElementById("grafico"), {
                        type: 'line',
                        data: {
                            labels: PegarDatas(dados),
                            datasets: [{
                                label: "Preço por produto",
                                data: PegarValores(dados),
                                backgroundColor: "#fff",
                                borderColor: "#c23616",
                                pointBackgroundColor: "#c23616",
                                pointBorderColor: "#c23616",
                                pointStyle: 'circle',
                                fill: false,
                                lineTension: 0,
                                spanGaps: true
                            }]
                        },

                        options: {
                            animation: {
                                easing: "linear",
                            },

                            legend: {
                                labels: {
                                    usePointStyle: true
                                }
                            },

                            scales: {
                                xAxes: [{
                                    gridLines: {
                                        display: false
                                    }
                                }],

                                yAxes: [{
                                    gridLines: {
                                        display: false
                                    }
                                }]
                            }
                        }

                    })
                }
            })
        }

        function PegarDatas(dados) {
            let indice = 0;
            let datas = [];

            while (indice < dados.length) {
                datas.push('' + dados[indice].dia + '/' + dados[indice].mes + '/' + dados[indice].ano);
                indice = indice + 1;
            }

            return datas;
        }

        function PegarValores(dados) {
            let indice = 0;
            let valores = [];

            while (indice < dados.length) {
                valores.push(dados[indice].valor);
                indice = indice + 1;
            }

            return valores;
        }
    </script>
}

RastradorPreco/Views/Produtos/Index.cshtml
@model IEnumerable<RastradorPreco.Models.Produto>

@{
    ViewData["Title"] = "Produtos cadastrados";
}


<p>
    <a asp-action="NovoProduto" class="btn btn-outline-success btn-sm">Novo Produto</a>
</p>
<table class="table table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th>
                #
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkProduto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProdutoId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    <a href="@item.LinkProduto">Link do produto</a>
                </td>
                <td>
                    <div class="row">
                        <a asp-controller="Produtos" asp-action="AtualizarProduto" asp-route-produtoId="@item.ProdutoId" class="btn btn-primary btn-sm rounded-circle">
                            <i class="fa fa-pencil-square-o"></i>
                        </a>

                        <a asp-controller="Produtos" asp-action="DetalhesProduto" asp-route-produtoId="@item.ProdutoId" class="btn btn-secondary btn-sm rounded-circle">
                            <i class="fa fa-tasks"></i>
                        </a>

                        <form asp-controller="Produtos" asp-action="ExcluirProduto" asp-route-produtoId="@item.ProdutoId" onclick="confirm('Prosseguir com a exclusão do produto @item.Nome ?')">
                            <button type="submit" class="btn btn-danger btn-sm rounded-circle"><i class="fa fa-times-circle"></i></button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

RastradorPreco/Views/Produtos/NovoProduto.cshtml
@model RastradorPreco.Models.Produto

@{
    ViewData["Title"] = "Novo Produto";
}

<h4>Novo Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NovoProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label col-form-label-sm"></label>
                <input asp-for="Nome" class="form-control form-control-sm" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkProduto" class="control-label col-form-label-sm"></label>
                <input asp-for="LinkProduto" class="form-control form-control-sm" />
                <span asp-validation-for="LinkProduto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-outline-success btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Voltar</a>
            </div>
        </form>
    </div>
</div>